// Copyright 2026 Sam Windell
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Node.js code for Floe license key signing for encrypted packages (.floe-pkg-enc).
//
// A license key is a signed blob containing the symmetric content key needed to decrypt a package. 
// See src/common_infrastructure/license.hpp for the full format description.

import crypto from 'node:crypto';

// Constants exactly matching Floe's source code.
const LICENSE_MAGIC = 0x4b4c4c46;
const LICENSE_VERSION = 1;
const PACKAGE_KEY_SIZE = 32;
const BEGIN_DELIMITER = ':FLOE PACKAGE LICENSE';
const END_DELIMITER = ':END';

/**
 * Sign a license key for a customer.
 * @param {Buffer} secretKey - 64-byte Ed25519 secret key (raw bytes, as generated by floe-license-tool)
 * @param {string} packageKeyHex - 64-character hex string (the 32-byte content key used to encrypt the package)
 * @param {string} email - customer email address
 * @returns {string} the complete license key text block
 */
export function signLicenseKey(secretKey, packageKeyHex, email) {
    if (!(secretKey instanceof Buffer) || secretKey.length !== 64)
        throw new Error('secretKey must be a 64-byte Buffer');

    const packageKey = Buffer.from(packageKeyHex, 'hex');
    if (packageKey.length !== PACKAGE_KEY_SIZE)
        throw new Error(`packageKeyHex must be a ${PACKAGE_KEY_SIZE * 2}-character hex string`);

    const emailBuf = Buffer.from(email, 'utf-8');
    if (emailBuf.length > 256)
        throw new Error('email must be 256 bytes or fewer');

    // Build payload: magic(4) + version(1) + content_key(32) + email_len(2) + email
    const payloadSize = 4 + 1 + PACKAGE_KEY_SIZE + 2 + emailBuf.length;
    const payload = Buffer.alloc(payloadSize);
    let offset = 0;

    payload.writeUInt32LE(LICENSE_MAGIC, offset); offset += 4;
    payload.writeUInt8(LICENSE_VERSION, offset); offset += 1;
    packageKey.copy(payload, offset); offset += PACKAGE_KEY_SIZE;
    payload.writeUInt16LE(emailBuf.length, offset); offset += 2;
    emailBuf.copy(payload, offset);

    // Sign with Ed25519. Node's crypto.sign needs a PKCS8-wrapped key.
    const pkcs8Key = wrapEd25519SecretKeyAsPkcs8(secretKey.subarray(0, 32));
    const signature = crypto.sign(null, payload, pkcs8Key);

    // Concatenate payload + signature, base64 encode
    const blob = Buffer.concat([payload, signature]);
    const b64 = blob.toString('base64');

    // Wrap in delimiters with lines
    const lines = (b64.match(/.{1,48}/g) ?? []).join('\n');
    return `${BEGIN_DELIMITER}\n${lines}\n${END_DELIMITER}\n`;
}

// Node's crypto.sign expects keys in PKCS8 format, but floe-license-tool outputs raw 64-byte
// keys (32-byte seed + 32-byte public key). For Ed25519, the PKCS8 encoding is always the same
// fixed 16-byte header followed by the 32-byte seed. These bytes come from the ASN.1 DER
// encoding defined in RFC 8410 (https://www.rfc-editor.org/rfc/rfc8410).
/**
 * @param {Buffer<ArrayBufferLike> | Uint8Array<ArrayBufferLike>} seed
 */
function wrapEd25519SecretKeyAsPkcs8(seed) {
    const prefix = Buffer.from([
        0x30, 0x2e,             // SEQUENCE (46 bytes total)
        0x02, 0x01, 0x00,       // INTEGER 0 (version)
        0x30, 0x05,             // SEQUENCE (5 bytes)
        0x06, 0x03, 0x2b, 0x65, 0x70, // OID 1.3.101.112 (Ed25519)
        0x04, 0x22,             // OCTET STRING (34 bytes)
        0x04, 0x20,             // OCTET STRING (32 bytes = the seed)
    ]);
    const der = Buffer.concat([prefix, seed]);
    return crypto.createPrivateKey({ key: der, format: 'der', type: 'pkcs8' });
}
