# Copyright 2026 Sam Windell
# SPDX-License-Identifier: GPL-3.0-or-later

name: Benchmarks

on:
  push:
    branches:
      - develop

env:
  ZIG_GLOBAL_CACHE_DIR: .zig-cache-global
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  benchmark:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: bencherdev/bencher@main

      - name: Run benchmarks and track with Bencher
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
        run: nix develop --command zig build script:benchmark-ci
